// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace GHLearning.Lifetimes.Repositories.Entities;

public partial class Todolist
{
    /// <summary>
    /// 識別碼
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// 標題
    /// </summary>
    public string Title { get; set; } = null!;

    /// <summary>
    /// 內容
    /// </summary>
    public string Content { get; set; } = null!;

    /// <summary>
    /// 狀態(1:待處理 2:已完成 3:已刪除)
    /// </summary>
    public sbyte Status { get; set; }

    /// <summary>
    /// 創建時間
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// 最後更新時間
    /// </summary>
    public DateTime UpdatedAt { get; set; }
}