// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using GHLearning.Lifetimes.Migrations.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace GHLearning.Lifetimes.Migrations.Entities.Configurations
{
    public partial class TodolistConfiguration : IEntityTypeConfiguration<Todolist>
    {
        public void Configure(EntityTypeBuilder<Todolist> entity)
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("todolist")
                .UseCollation("utf8mb4_general_ci");

            entity.Property(e => e.Id)
                .HasComment("識別碼")
                .HasColumnName("id")
                .UseCollation("ascii_general_ci")
                .HasCharSet("ascii");
            entity.Property(e => e.Content)
                .HasComment("內容")
                .HasColumnType("text")
                .HasColumnName("content");
            entity.Property(e => e.CreatedAt)
                .HasMaxLength(6)
                .HasDefaultValueSql("CURRENT_TIMESTAMP(6)")
                .HasComment("創建時間")
                .HasColumnName("created_at");
            entity.Property(e => e.Status)
                .HasComment("狀態(1:待處理 2:已完成 3:已刪除)")
                .HasColumnName("status");
            entity.Property(e => e.Title)
                .HasMaxLength(255)
                .HasComment("標題")
                .HasColumnName("title");
            entity.Property(e => e.UpdatedAt)
                .HasMaxLength(6)
                .ValueGeneratedOnAddOrUpdate()
                .HasDefaultValueSql("CURRENT_TIMESTAMP(6)")
                .HasComment("最後更新時間")
                .HasColumnName("updated_at");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Todolist> entity);
    }
}
